# 彩虹易支付 CNB.Cool 流水线
# 镜像: docker.cnb.cool/aliveranme/epay

.docker-build: &docker-build
  services:
    - docker
  stages:
    - name: set tag
      script: |
        if [ -n "${VERSION}" ]; then
          TAG="${VERSION}"
        elif [ "${CNB_PIPELINE_EVENT}" = "tag_push" ]; then
          TAG="${CNB_BRANCH}"
        else
          TAG="latest"
        fi
        IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${TAG}-${PLATFORM_ARCH}"
        echo -n "${IMAGE}"
      exports:
        info: IMAGE_TAG
    - name: build
      script: docker build -t "${IMAGE_TAG}" .
    - name: push
      script: docker push "${IMAGE_TAG}"

main:
  push:
    - <<: *docker-build
      name: build-amd64
      runner: {tags: "cnb:arch:amd64"}
      env: {PLATFORM_ARCH: "linux-amd64"}
    - <<: *docker-build
      name: build-arm64
      runner: {tags: "cnb:arch:arm64:v8"}
      env: {PLATFORM_ARCH: "linux-arm64"}
    - name: merge-manifest
      runner: {tags: "cnb:arch:amd64"}
      stages:
        - name: merge
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64

$:
  tag_push:
    - <<: *docker-build
      name: build-amd64
      runner: {tags: "cnb:arch:amd64"}
      env: {PLATFORM_ARCH: "linux-amd64"}
    - <<: *docker-build
      name: build-arm64
      runner: {tags: "cnb:arch:arm64:v8"}
      env: {PLATFORM_ARCH: "linux-arm64"}
    - name: merge-manifest
      runner: {tags: "cnb:arch:amd64"}
      stages:
        - name: merge-version
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: merge-latest
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64

"**":
  api_trigger_build:
    - <<: *docker-build
      name: build-amd64
      runner: {tags: "cnb:arch:amd64"}
      env: {PLATFORM_ARCH: "linux-amd64"}
    - <<: *docker-build
      name: build-arm64
      runner: {tags: "cnb:arch:arm64:v8"}
      env: {PLATFORM_ARCH: "linux-arm64"}
    - name: merge-manifest
      runner: {tags: "cnb:arch:amd64"}
      stages:
        - name: merge-version
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${VERSION}
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${VERSION}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: merge-latest
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${VERSION}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
